Number of chars
CryptoSFor/str pull request #1
Opened 2021-10-21 09:11 UTC by CryptoSFor

2021-10-21 13:34 UTC, xartishuk commented
`readme.md` should have info inside. `.gitignore` should have stuff inside too

2021-10-21 13:37 UTC, xartishuk commented
rename the repo, "task1" won't do. Same goes for the package

2021-10-21 13:40 UTC, xartishuk commented
commit messages should be descriptive. Here's a link from general requirements: https://chris.beams.io/posts/git-commit/

2021-10-21 13:41 UTC, xartishuk commented
if you want to version your code, you should take a look at git tags

2021-10-21 13:41 UTC, xartishuk requested changes
see comments

2021-10-21 14:48 UTC, xartishuk requested changes

2021-10-21 14:48 UTC, xartishuk commented on README.md
> +This project contains two functions "NumberOfCharacters" and "ReverseString", the first you can use to count characters in a string, the second to reverse the string. Also, both functions were covere
you can use 
>`



symbol to denote code, like so: 
`NumberOfCharacters`

2021-10-21 14:48 UTC, xartishuk commented on task1.go
> +func NumberOfCharacters(s string) int {
add a comment

2021-10-21 14:49 UTC, xartishuk commented
+ rename the file from task1.go to smth else

2021-10-21 15:08 UTC, CryptoSFor commented on README.md
> +This project contains two functions "NumberOfCharacters" and "ReverseString", the first you can use to count characters in a string, the second to reverse the string. Also, both functions were covere
Done

2021-10-21 15:08 UTC, CryptoSFor commented on task1.go
> +func NumberOfCharacters(s string) int {
Done

2021-10-21 15:13 UTC, xartishuk commented on task1.go
> +func NumberOfCharacters(s string) int {
is it? don't see it

2021-10-21 15:40 UTC, CryptoSFor commented on task1.go
> +func NumberOfCharacters(s string) int {
Done!

2021-10-22 14:50 UTC, xartishuk commented
comments look good. The rename `str.go -> number_of_chars.go` doesn't look good. Try to avoid long file names. `str.go, string.go, strings.go, char.go, charnum.go, char-num.go, char_num.go, charNum.go` are all fine

2021-10-22 14:51 UTC, xartishuk approved these changes

2021-10-22 16:06 UTC, merged